Name:		i2c-tools
Version:	3.0.2
Release:	1
Summary:	Heterogeneous set of I2C tools for Linux
Group:		System/Libraries
License:	GPLv2+
Source0:	http://dl.lm-sensors.org/i2c-tools/releases/%{name}-%{version}.tar.bz2
# Patches auto-generated by git-buildpackage:

%description
This package contains a heterogeneous set of I2C tools for Linux: a bus
probing tool, a chip dumper, register-level access helpers, EEPROM
decoding scripts, and more.

%package -n libi2c-devel
Summary: Userspace I2C programming library development files

%description -n libi2c-devel
I2C devices are usually controlled by a kernel driver. Using this
library it is also possible to access all devices on an adapter
from userspace and without the knowledge of Linux kernel internals.

%prep
%setup -q -n %{name}-%{version}

%build
make prefix=%{_prefix}

%install
make install DESTDIR=$RPM_BUILD_ROOT prefix=%{_prefix}

# To avoid conflicts with kernel package lets move this header to
# different directory.
mkdir -p $RPM_BUILD_ROOT%{_includedir}/libi2c
mv $RPM_BUILD_ROOT%{_includedir}/linux/i2c-dev.h $RPM_BUILD_ROOT%{_includedir}/libi2c/

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc COPYING
%{_bindir}/*
%{_sbindir}/*
%{_mandir}/man8/*

%files -n libi2c-devel
%defattr(-,root,root,-)
%doc COPYING
%{_includedir}/libi2c/i2c-dev.h
